WiP

diff --git a/run_onchange_install-packages.sh.tmpl b/run_onchange_install-packages.sh.tmpl
--- a/run_onchange_install-packages.sh.tmpl
+++ b/run_onchange_install-packages.sh.tmpl
@@ -43,40 +43,44 @@ log() {
 
 exec > >(tee -a "$LOGFILE") 2>&1
 
+os=$(uname)
+cwd=$HOME/.local/share/chezmoi
+
 prepMac() {
-  # # Ensure Homebrew is installed
+  # Ensure Homebrew is installed
   # if ! command -v brew &> /dev/null; then
-  #   echo "Homebrew is not installed. Installing..."
+  #   log "Homebrew is not installed. Installing..."
   #   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   # fi
 
   # # Ensure Chezmoi is installed
   # if ! command -v chezmoi &> /dev/null; then
-  #     echo "Chezmoi is not installed. Installing..."
-  #     brew install chezmoi
+  #   log "Chezmoi is not installed. Installing..."
+  #   brew install chezmoi
+  #   if ! command -v chezmoi &> /dev/null; then
+  #     log "Failed to install Chezmoi. Exiting..."
+  #     exit 1
+  #   fi
   # fi
 
-  if ! [ -f $HOME/.config/vault/key.age ]; then
-    echo "Decryption key missing - exiting..."
+  if ! [ -f "$HOME/.config/vault/key.age" ]; then
+    log "Decryption key missing - exiting..."
     exit 1
   else
-    exec "$cwd/zx/mac.mjs"
+    log "Executing mac.mjs..."
+    "$cwd/zx/mac.mjs"
   fi
 }
 
 log "Installation started..."
 
-os=$(uname)
-cwd=$HOME/.local/share/chezmoi
-
 if [[ "$os" == "Linux" ]]; then
-  echo "Linux"
+  log "Linux"
 elif [[ "$os" == "Darwin" ]]; then
-  echo "MacOS"
-  prepMac()
+  log "MacOS"
+  prepMac
 elif [[ "$os" == "Windows" ]]; then
-  echo "Windows"
+  log "Windows"
 else
-  echo "Unknown OS"
+  log "Unknown OS"
 fi
-
